name: PR checks

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    uses: hippoo-app/devops-templates/.github/workflows/validate-plugin.yml@main
    with:
      plugin-slug: hippoo-shippo-integration-for-woocommerce
